language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  strategy: git
  os: linux
  provider: pages
  cleanup: true
  dist: xenial
  token: $github_token
  local_dir: build
  on:
    branch: main
