language: node_js
node_js:
  - "stable"
os: linux
dist: xenial
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  token: $github_token
  local_dir: build
  on:
    branch: main
